AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Elastic File System
  
  
  

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Description: This lambada Monitoring daily Monday to Friday At 9:00 pm and send the sns if instance is running
Resources:
  MyLambda:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 21 * * ? *)
            Enabled: True 

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MyLambda:
    Description: "MyLambda Lambda Function ARN"
    Value: !GetAtt MyLambda.Arn
  MyLambdaIamRole:
    Description: "Implicit IAM Role created for MyLambda function"
    Value: !GetAtt MyLambdaRole.Arn
